services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: exchange_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./DBschema.sql:/docker-entrypoint-initdb.d/DBschema.sql

  backend:
    build: ./exchange-app-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/exchange_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./exchange-app-frontend
      args:
        REACT_APP_API_URL: http://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
